POST http://localhost:8080/storeFile HTTP/1.1
content-type: application/json

{
    "data":"Hello World"
}

POST http://localhost:8080/createUri HTTP/1.1
content-type: application/json

{
    "data":{"name":"guy","description":"Freddy"}
}

POST https://mynftnotary-jsu7sc3kfa-uc.a.run.app/storeFile HTTP/1.1
content-type: application/json

{
    "data":"Hello World"
}